Updates

diff --git a/dot-local/bin/vv b/dot-local/bin/vv
--- a/dot-local/bin/vv
+++ b/dot-local/bin/vv
@@ -8,60 +8,61 @@
 #   environment variable is set to true. Finally, it runs the built nightly Neovim
 #   binary with the provided arguments.
 
-set -e  # Exit immediately if a command exits with a non-zero status
+set -e # Exit immediately if a command exits with a non-zero status
+set -x
 
-  repo="$HOME/code/github.com/neovim/neovim.git/master"
-  vim_runtime="$repo/runtime"
-  nvim_app_name="nvim"
-  nvim_nightly_bin="$repo/build/bin/nvim"
-  sha_file="/tmp/nvim_sha"
-  debug=${DEBUG:-false}
-  build_container="quay.io/fedora/fedora-minimal:41"
+repo="$HOME/code/github.com/neovim/neovim.git/master"
+vim_runtime="$repo/runtime"
+nvim_app_name="nvim"
+nvim_nightly_bin="$repo/build/bin/nvim"
+sha_file="/tmp/nvim_sha"
+debug=${DEBUG:-false}
+build_container="quay.io/fedora/fedora-minimal:41"
 
-  if [[ ! -f "$repo/README.md" ]]; then
-    echo "Error: Neovim git repo not found at $repo" >&2
-    exit 1
+if [[ ! -f "$repo/README.md" ]]; then
+  echo "Error: Neovim git repo not found at $repo" >&2
+  exit 1
+fi
+
+# TODO: Update this to check if the sha_file was modified over 24h ago
+skip_update=0
+if [[ -e "$sha_file" ]]; then
+  if find "$sha_file" -type f -newermt "$(date +%Y-%m-%d)" | grep -q .; then
+    [[ "$debug" == "true" ]] && echo "Update skipped: $sha_file modified today."
+    skip_update=1
   fi
+fi
 
-  # TODO: Update this to check if the sha_file was modified over 24h ago
-  skip_update=0
-  if [[ -e "$sha_file" ]]; then
-    if find "$sha_file" -type f -newermt "$(date +%Y-%m-%d)" | grep -q .; then
-      [[ "$debug" == "true" ]] && echo "Update skipped: $sha_file modified today."
-      skip_update=1
+if [[ "$skip_update" -eq 0 ]]; then
+  if socat -T1 - tcp:github.com:443 >&/dev/null; then
+    pushd "$repo"
+    git fetch --all --force
+    if [[ -x "$nvim_nightly_bin" ]]; then
+      mv "$nvim_nightly_bin" "$nvim_nightly_bin"-old
     fi
-  fi
+    git pull -f upstream master
 
-  if [[ "$skip_update" -eq 0 ]]; then
-    if socat -T1 - tcp:github.com:443 >& /dev/null; then
-      pushd "$repo"
-      git fetch --all --force
-        if [[ -x "$nvim_nightly_bin" ]]; then
-          mv "$nvim_nightly_bin" "$nvim_nightly_bin"-old
-        fi
-        git pull -f upstream master
-
-        # Note: On linux, build in container
-	if [[ "$(uname)" != "Darwin" ]]; then
-          podman run --rm -it -v "$PWD:/workdir" \
-            -w /workdir \
-            "$build_container" \
-            bash -c 'microdnf install --nogpgcheck -y ninja-build cmake gcc make gettext curl glibc-gconv-extra git && make CMAKE_BUILD_TYPE=Release'
-        else
-          make CMAKE_BUILD_TYPE=Release
-        fi
-      popd
+    # Note: On linux, build in container
+    if [[ "$(uname)" != "Darwin" ]]; then
+      podman run --rm -v "$PWD:/workdir" \
+        -w /workdir \
+        "$build_container" \
+        bash -c 'microdnf install --nogpgcheck -y ninja-build cmake gcc make gettext curl glibc-gconv-extra git && make CMAKE_BUILD_TYPE=Release'
     else
-      echo "Warning: github.com not reachable, skipping update." >&2
+      make CMAKE_BUILD_TYPE=Release
     fi
+    popd
+  else
+    echo "Warning: github.com not reachable, skipping update." >&2
   fi
+fi
 
-  if [[ ! -x "$nvim_nightly_bin" ]]; then
-    echo "Error: Neovim nightly binary not found or not executable at $nvim_nightly_bin" >&2
-    exit 1
-  fi
-  echo 1 > "$sha_file"
+if [[ ! -x "$nvim_nightly_bin" ]]; then
+  echo "Error: Neovim nightly binary not found or not executable at $nvim_nightly_bin" >&2
+  exit 1
+fi
+echo 1 >"$sha_file"
 
-  VIMRUNTIME="$vim_runtime" NVIM_APPNAME="$nvim_app_name" "$nvim_nightly_bin" "$@"
+VIMRUNTIME="$vim_runtime" NVIM_APPNAME="$nvim_app_name" "$nvim_nightly_bin" "$@"
 
 # vim: set ft=bash:
