Updates

diff --git a/dot-local/bin/vv b/dot-local/bin/vv
--- a/dot-local/bin/vv
+++ b/dot-local/bin/vv
@@ -8,7 +8,7 @@
 #   environment variable is set to true. Finally, it runs the built nightly Neovim
 #   binary with the provided arguments.
 
-# set -e  # Exit immediately if a command exits with a non-zero status
+set -e  # Exit immediately if a command exits with a non-zero status
 
   repo="$HOME/code/github.com/neovim/neovim.git/master"
   vim_runtime="$repo/runtime"
@@ -35,18 +35,14 @@
   if [[ "$skip_update" -eq 0 ]]; then
     if socat -T1 - tcp:github.com:443 >& /dev/null; then
       pushd "$repo"
-      git fetch upstream
-      # TODO: update to check if local head sha is different to upstream/master head
-      #if git diff --quiet HEAD..origin/$(git rev-parse --abbrev-ref HEAD); then
-      if true; then
+      git fetch --all --force
         if [[ -x "$nvim_nightly_bin" ]]; then
           mv "$nvim_nightly_bin" "$nvim_nightly_bin"-old
         fi
-        git rev-parse HEAD > "$sha_file"
-        git pull --ff-only origin "$(git rev-parse --abbrev-ref HEAD)"
+        git pull -f upstream master
 
         # Note: On linux, build in container
-        if [ "$uname" != "Darwin" ]; then
+	if [[ "$(uname)" != "Darwin" ]]; then
           podman run --rm -it -v "$PWD:/workdir" \
             -w /workdir \
             "$build_container" \
@@ -54,7 +50,6 @@
         else
           make CMAKE_BUILD_TYPE=Release
         fi
-      fi
       popd
     else
       echo "Warning: github.com not reachable, skipping update." >&2
@@ -65,8 +60,8 @@
     echo "Error: Neovim nightly binary not found or not executable at $nvim_nightly_bin" >&2
     exit 1
   fi
+  echo 1 > "$sha_file"
 
   VIMRUNTIME="$vim_runtime" NVIM_APPNAME="$nvim_app_name" "$nvim_nightly_bin" "$@"
-
 
 # vim: set ft=bash:
